# Generated by Django 3.0.2 on 2020-02-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
